name: amarinthui
services:
  frontend:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: "6442450944"
    image: nginx:latest
    container_name: amarinthui-frontend
    networks:
      - amarinthui
    depends_on:
      - backend
    ports:
      - mode: ingress
        target: 80
        published: "8090"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./html
        target: /usr/share/nginx/html
        bind:
          create_host_path: true
      - type: bind
        source: ./conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        bind:
          create_host_path: true
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: amarinthui-backend:latest
    restart: unless-stopped
    working_dir: /app
    volumes:
      - type: bind
        source: ./api
        target: /app
    networks:
      - amarinthui
    environment:
      - ORT_LOGGING_LEVEL=3
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: amarinthui-qdrant
    restart: unless-stopped
    networks:
      - amarinthui
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - type: bind
        source: ./qdrant_storage
        target: /qdrant/storage
        bind:
          create_host_path: true
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
networks:
  amarinthui:
    driver: bridge
